// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.instance.web.edit;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import java.util.List;

import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;

import com.systemsjr.motshelo.instance.member.vo.InstanceMemberVO;
import com.systemsjr.motshelo.instance.vo.MotsheloInstanceVO;
import com.systemsjr.motshelo.loan.vo.LoanVO;
import com.systemsjr.motshelo.member.MemberStatus;
import com.systemsjr.motshelo.member.vo.MemberVO;
import com.systemsjr.motshelo.vo.MotsheloVO;

/**
 * @see com.systemsjr.motshelo.instance.web.edit.MotsheloInstanceEditController
 */
public class MotsheloInstanceEditControllerImpl
    extends MotsheloInstanceEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8087502174420736204L;

    /**
     * @see com.systemsjr.motshelo.instance.web.edit.MotsheloInstanceEditController#doSaveMotsheloInstance()
     */
    @Override
    public void doSaveMotsheloInstance()
    {
    	MotsheloInstanceVO motsheloInstanceVO = getEditMotsheloInstanceSaveForm().getMotsheloInstanceVO();
    	motsheloInstanceVO.setMotshelo(motsheloInstanceVO.getMotshelo());
    	motsheloInstanceVO.setInstanceName("-");  	
    	motsheloInstanceVO = getMotsheloInstanceService().saveMotsheloInstance(motsheloInstanceVO);
    	getEditMotsheloInstanceSaveForm().setMotsheloInstanceVO(motsheloInstanceVO);
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("motsheloInstanceVO", getEditMotsheloInstanceSaveForm().getMotsheloInstanceVO());
    }


    /**
     * @see com.systemsjr.motshelo.instance.web.edit.MotsheloInstanceEditController#doNewMotsheloInstance()
     */
    @Override
    public void doNewMotsheloInstance()
    {
    	MotsheloInstanceVO motsheloInstanceVO = new MotsheloInstanceVO();
    	getEditMotsheloInstanceSaveForm().setMotsheloInstanceVO(motsheloInstanceVO);
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.edit.MotsheloInstanceEditController#doInitialiseEditScreen(MotsheloInstanceVO motsheloInstanceVO)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
    	
    	Collection<MotsheloVO> metshelo = getMotsheloService().getAllMetshelo();
    	Collection<SelectItem> metsheloBackingList = new ArrayList<SelectItem>();
    	metsheloBackingList.add(new SelectItem(-1, "--NONE--"));
    	for(MotsheloVO motshelo : metshelo)
    	{
    		metsheloBackingList.add(new SelectItem(motshelo.getId(), motshelo.getName()));
    	}
    	form.setMotsheloInstanceVOMotsheloBackingList(metsheloBackingList);
    	getEditMotsheloInstanceSaveForm().setMotsheloInstanceVOMotsheloBackingList(metsheloBackingList);
    	    	
    	MotsheloInstanceVO motsheloInstanceVO = (MotsheloInstanceVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("motsheloInstanceVO");
    	if(motsheloInstanceVO == null)
    	{
    		motsheloInstanceVO = new MotsheloInstanceVO();
    	} 
    	
    	if(motsheloInstanceVO.getMotshelo() == null)
    	{
    		motsheloInstanceVO.setMotshelo(new MotsheloVO());
    	}
    	
    	Collection<SelectItem> memberBackingList = new ArrayList<SelectItem>();
    	MotsheloVO motshelo = getMotsheloService().findById(motsheloInstanceVO.getMotshelo().getId());
    	if(motshelo != null) {
	    	for(MemberVO member : motshelo.getMembers())
	    	{
	    		if(member.getStatus() == MemberStatus.ACTIVE) {
	    			memberBackingList.add(new SelectItem(member.getId(), member.getName() + " " + member.getSurname()));
	    		}
	    	}
    	}
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("memberBackingList", memberBackingList);
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("selectedMember", new MemberVO());
    	
    	form.setMotsheloInstanceVO(motsheloInstanceVO); 
    	
    	LoanVO loanVO = new LoanVO();
    	loanVO.setMotsheloInstance(motsheloInstanceVO);
    	loanVO.setInstanceMember(new InstanceMemberVO());
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("loanVO", loanVO);
    	
    }


	@Override
	public void doAddMember(DoAddMemberForm form) throws Throwable {
		MemberVO member = (MemberVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("selectedMember");
		member = getMemberService().findById(member.getId());
		InstanceMemberVO instanceMember = new InstanceMemberVO();
		instanceMember.setMember(member);
		instanceMember.setMotsheloInstance(getEditMotsheloInstanceSaveForm().getMotsheloInstanceVO());
		instanceMember.setBalance(new BigDecimal(0.00));
		instanceMember = getInstanceMemberService().saveInstanceMember(instanceMember);
		
		if(instanceMember.getId() != null)
		{
			getEditMotsheloInstanceSaveForm().getMotsheloInstanceVO().getInstanceMembers().add(instanceMember);
		}
	}


	@Override
	public List getMemberBackingList() throws Throwable {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	public void doAddLoan() throws Throwable {
		LoanVO loanVO = (LoanVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("loanVO");
		
	}

}