// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.loan.web.details;

import java.util.Date;

import com.systemsjr.motshelo.loan.vo.LoanVO;

/**
 * @see com.systemsjr.motshelo.loan.web.details.LoanDetailsController
 */
public class LoanDetailsControllerImpl
    extends LoanDetailsController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 7036407180856061850L;

    /**
     * @see com.systemsjr.motshelo.loan.web.details.LoanDetailsController#doInitialiseDetailsScreen(LoanVO loanVO)
     */
    @Override
    public void doInitialiseDetailsScreen(DoInitialiseDetailsScreenForm form)
    {
        // populating value with dummy instance
        LoanVO loanVO = new LoanVO();
        loanVO.setId(new Long((long)3355));
        loanVO.setInstanceMember(null);
        loanVO.setAmount(null);
        loanVO.setStartDate(new Date());
        loanVO.setExpectedEndDate(new Date());
        loanVO.setActualEndDate(new Date());
        loanVO.setBalance(null);
        loanVO.setStatus(null);
        loanVO.setMotsheloInstance(null);
        loanVO.setInterests(null);
        form.setLoanVO(loanVO);
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.details.LoanDetailsController#doLoanEdit(LoanVO loanVO)
     */
    @Override
    public void doLoanEdit(DoLoanEditForm form)
    {
        // populating value with dummy instance
        LoanVO loanVO = new LoanVO();
        loanVO.setId(new Long((long)3355));
        loanVO.setInstanceMember(null);
        loanVO.setAmount(null);
        loanVO.setStartDate(new Date());
        loanVO.setExpectedEndDate(new Date());
        loanVO.setActualEndDate(new Date());
        loanVO.setBalance(null);
        loanVO.setStatus(null);
        loanVO.setMotsheloInstance(null);
        loanVO.setInterests(null);
        form.setLoanVO(loanVO);
    }

}