// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.instance.member.web.edit;

import java.util.ArrayList;
import java.util.Collection;

import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;

import com.systemsjr.motshelo.instance.member.vo.InstanceMemberVO;
import com.systemsjr.motshelo.instance.vo.MotsheloInstanceVO;
import com.systemsjr.motshelo.member.vo.MemberVO;
import com.systemsjr.motshelo.vo.MotsheloVO;

/**
 * @see com.systemsjr.motshelo.instance.member.web.edit.InstanceMemberEditController
 */
public class InstanceMemberEditControllerImpl extends InstanceMemberEditController {
	/**
	 * The serial version UID of this class. Needed for serialization.
	 */
	private static final long serialVersionUID = 3025785027924407078L;

	/**
	 * @see com.systemsjr.motshelo.instance.member.web.edit.InstanceMemberEditController#doSaveInstanceMember()
	 */
	@Override
	public void doSaveInstanceMember() {
		InstanceMemberVO member = getEditInstanceMemberSaveForm().getInstanceMemberVO();
		member = getInstanceMemberService().saveInstanceMember(member);
		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("instanceMemberVO", member);
	}

	/**
	 * @see com.systemsjr.motshelo.instance.member.web.edit.InstanceMemberEditController#doNewInstanceMember()
	 */
	@Override
	public void doNewInstanceMember() {
		InstanceMemberVO member = new InstanceMemberVO();
		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("instanceMemberVO", member);
	}

	/**
	 * @see com.systemsjr.motshelo.instance.member.web.edit.InstanceMemberEditController#doInitialiseEditScreen(InstanceMemberVO
	 *      instanceMemberVO)
	 */
	@Override
	public void doInitialiseEditScreen(DoInitialiseEditScreenForm form) {
		
		InstanceMemberVO member = (InstanceMemberVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("instanceMemberVO");
		if(member == null)
		{
			member = form.getInstanceMemberVO();
		}
		form.setInstanceMemberVO(member);
		getEditInstanceMemberSaveForm().setInstanceMemberVO(member);
		if(member.getMember() == null)
		{
			member.setMember(new MemberVO());
		}

		if(member.getMotsheloInstance() == null)
		{
			member.setMotsheloInstance(new MotsheloInstanceVO());
		}

		Collection<SelectItem> motsheloInstanceBackingList = new ArrayList<SelectItem>();
		for(MotsheloInstanceVO instance : getMotsheloInstanceService().getAllMotsheloInstances())
		{
			motsheloInstanceBackingList.add(new SelectItem(instance.getId(), instance.getInstanceName()));
		}

		form.setInstanceMemberVOMotsheloInstanceBackingList(motsheloInstanceBackingList);
		getEditInstanceMemberSaveForm().setInstanceMemberVOMotsheloInstanceBackingList(motsheloInstanceBackingList);
		
		try {
			updateEditForm();
		} catch (Throwable e) {
			e.printStackTrace();
		}
	}

	/**
	 * @see com.systemsjr.motshelo.instance.member.web.edit.InstanceMemberEditController#doAddTransaction(MemberVO
	 *      member)
	 */
	@Override
	public void doAddTransaction(DoAddTransactionForm form) {

	}

	/**
	 * @see com.systemsjr.motshelo.instance.member.web.edit.InstanceMemberEditController#doAddLoan()
	 */
	@Override
	public void doAddLoan() {
	}

	/**
	 * @see com.systemsjr.motshelo.instance.member.web.edit.InstanceMemberEditController#updateInstanceMember()
	 */
	@Override
	public void updateInstanceMember() {
	}

	@Override
	public void updateEditForm() throws Throwable {
		
		InstanceMemberVO instanceMemberVO = getEditInstanceMemberSaveForm().getInstanceMemberVO();
		
		if(instanceMemberVO.getMotsheloInstance() != null && instanceMemberVO.getMotsheloInstance().getId() != null) {
			MotsheloInstanceVO instance = getMotsheloInstanceService().findById(instanceMemberVO.getMotsheloInstance().getId());
			MotsheloVO motshelo = getMotsheloService().findById(instance.getMotshelo().getId());
			Collection<SelectItem> memberBackingList = new ArrayList<SelectItem>();
			for(MemberVO member : motshelo.getMembers())
			{
				memberBackingList.add(new SelectItem(member.getId(), member.getName() + " " + member.getSurname()));
			}
			
			getEditInstanceMemberSaveForm().setInstanceMemberVOMemberBackingList(memberBackingList);
		}
	}

}