// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.transaction.web.details;

import java.util.Date;

import com.systemsjr.motshelo.transaction.vo.TransactionVO;

/**
 * @see com.systemsjr.motshelo.transaction.web.details.TransactionDetailsController
 */
public class TransactionDetailsControllerImpl
    extends TransactionDetailsController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 5129968490304310803L;

    /**
     * @see com.systemsjr.motshelo.transaction.web.details.TransactionDetailsController#doInitialiseDetailsScreen(TransactionVO transactionVO)
     */
    @Override
    public void doInitialiseDetailsScreen(DoInitialiseDetailsScreenForm form)
    {
        // populating value with dummy instance
        TransactionVO transactionVO = new TransactionVO();
        transactionVO.setId(new Long((long)3355));
        transactionVO.setTransactionDate(new Date());
        transactionVO.setTransactionAmount(null);
        transactionVO.setTransactionType(null);
        transactionVO.setTransactionMode(null);
        transactionVO.setInstanceMember(null);
        transactionVO.setMotsheloInstance(null);
        form.setTransactionVO(transactionVO);
    }

    /**
     * @see com.systemsjr.motshelo.transaction.web.details.TransactionDetailsController#doTransactionEdit(TransactionVO transactionVO)
     */
    @Override
    public void doTransactionEdit(DoTransactionEditForm form)
    {
        // populating value with dummy instance
        TransactionVO transactionVO = new TransactionVO();
        transactionVO.setId(new Long((long)3355));
        transactionVO.setTransactionDate(new Date());
        transactionVO.setTransactionAmount(null);
        transactionVO.setTransactionType(null);
        transactionVO.setTransactionMode(null);
        transactionVO.setInstanceMember(null);
        transactionVO.setMotsheloInstance(null);
        form.setTransactionVO(transactionVO);
    }

}