// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.loan.web.search;

/**
 * @see com.systemsjr.motshelo.loan.web.search.LoanSearchController
 */
public class LoanSearchControllerImpl
    extends LoanSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 3877559525103219476L;

    /**
     * @see com.systemsjr.motshelo.loan.web.search.LoanSearchController#enterInitialiseSearchScreen(com.systemsjr.motshelo.loan.vo.LoanSearchCriteria searchCriteria)
     */
    @Override
    public void enterInitialiseSearchScreen(EnterInitialiseSearchScreenForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.search.LoanSearchController#doInitialiseSearchScreen(com.systemsjr.motshelo.loan.vo.LoanSearchCriteria searchCriteria)
     */
    @Override
    public void doInitialiseSearchScreen(DoInitialiseSearchScreenForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.search.LoanSearchController#exitInitialiseSearchScreen(com.systemsjr.motshelo.loan.vo.LoanSearchCriteria searchCriteria)
     */
    @Override
    public void exitInitialiseSearchScreen(ExitInitialiseSearchScreenForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.search.LoanSearchController#enterLoanSearch()
     */
    @Override
    public void enterLoanSearch()
    {
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.search.LoanSearchController#doLoanSearch()
     */
    @Override
    public void doLoanSearch()
    {
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.search.LoanSearchController#exitLoanSearch()
     */
    @Override
    public void exitLoanSearch()
    {
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.search.LoanSearchController#enterLoanEdit(java.lang.Long id, com.systemsjr.motshelo.loan.vo.LoanVO loanVO)
     */
    @Override
    public void enterLoanEdit(EnterLoanEditForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.search.LoanSearchController#doLoanEdit(java.lang.Long id, com.systemsjr.motshelo.loan.vo.LoanVO loanVO)
     */
    @Override
    public void doLoanEdit(DoLoanEditForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.search.LoanSearchController#exitLoanEdit(java.lang.Long id, com.systemsjr.motshelo.loan.vo.LoanVO loanVO)
     */
    @Override
    public void exitLoanEdit(ExitLoanEditForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.search.LoanSearchController#enterLoanDetails(java.lang.Long id, com.systemsjr.motshelo.loan.vo.LoanVO loanVO)
     */
    @Override
    public void enterLoanDetails(EnterLoanDetailsForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.search.LoanSearchController#doLoanDetails(java.lang.Long id, com.systemsjr.motshelo.loan.vo.LoanVO loanVO)
     */
    @Override
    public void doLoanDetails(DoLoanDetailsForm form)
    {
       
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.search.LoanSearchController#exitLoanDetails(java.lang.Long id, com.systemsjr.motshelo.loan.vo.LoanVO loanVO)
     */
    @Override
    public void exitLoanDetails(ExitLoanDetailsForm form)
    {
       
    }

}