// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.transaction.web.search;

import java.util.Collection;

import javax.faces.context.FacesContext;

import com.systemsjr.motshelo.transaction.vo.TransactionSearchCriteria;
import com.systemsjr.motshelo.transaction.vo.TransactionVO;

/**
 * @see com.systemsjr.motshelo.transaction.web.search.TransactionSearchController
 */
public class TransactionSearchControllerImpl
    extends TransactionSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 2701783572994785197L;

    /**
     * @see com.systemsjr.motshelo.transaction.web.search.TransactionSearchController#doInitialiseSearchScreen(com.systemsjr.motshelo.transaction.vo.TransactionSearchCriteria searchCriteria)
     */
    @Override
    public void doInitialiseSearchScreen(DoInitialiseSearchScreenForm form)
    {
        TransactionSearchCriteria searchCriteria = new TransactionSearchCriteria();
        form.setSearchCriteria(searchCriteria);
    }

    /**
     * @see com.systemsjr.motshelo.transaction.web.search.TransactionSearchController#doTransactionsSearch()
     */
    @Override
    public void doTransactionsSearch()
    {
    	Collection<TransactionVO> transactions = getTransactionService().searchTransactions(getSearchTransactionsSearchForm().getSearchCriteria());
    	getSearchTransactionsSearchForm().setTransactions(transactions);
    }
    
    /**
     * @see com.systemsjr.motshelo.transaction.web.search.TransactionSearchController#doEditTransaction(java.lang.Long id, com.systemsjr.motshelo.transaction.vo.TransactionVO transactionVO)
     */
    @Override
    public void doEditTransaction(DoEditTransactionForm form)
    {
    	getSearchTransactionsForm().setId(form.getId());
    	try {
			TransactionVO transactionVO = getSelectedTransaction();
			form.setTransactionVO(transactionVO);
		} catch (Throwable e) {
			e.printStackTrace();
		}
    }

    /**
     * @see com.systemsjr.motshelo.transaction.web.search.TransactionSearchController#doTransactionDetails(java.lang.Long id, com.systemsjr.motshelo.transaction.vo.TransactionVO transactionVO)
     */
    @Override
    public void doTransactionDetails(DoTransactionDetailsForm form)
    {
    	getSearchTransactionsForm().setId(form.getId());
    	try {
			TransactionVO transactionVO = getSelectedTransaction();
			form.setTransactionVO(transactionVO);
		} catch (Throwable e) {
			e.printStackTrace();
		}
    }

	@Override
	protected TransactionVO getSelectedTransaction() throws Throwable {
		TransactionVO transactionVO = getTransactionService().findById(getSearchTransactionsForm().getId());		
		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("transactionVO", transactionVO);
		
		return transactionVO;
	}

}