// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on 12/19/2018 14:07:02+0200.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.systemsjr.motshelo.instance;

import com.systemsjr.motshelo.instance.vo.MotsheloInstanceSearchCriteria;
import com.systemsjr.motshelo.instance.vo.MotsheloInstanceVO;
import java.util.Collection;
import org.springframework.stereotype.Repository;

/**
 * @see MotsheloInstance
 */
@Repository
public class MotsheloInstanceDaoImpl
    extends MotsheloInstanceDaoBase
{
    /**
     * {@inheritDoc}
     */
    @Override
    protected Collection<MotsheloInstance> handleFindByCriteria(MotsheloInstanceSearchCriteria searchCriteria)
    {
        // TODO implement public Collection<MotsheloInstance> handleFindByCriteria(MotsheloInstanceSearchCriteria searchCriteria)
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toMotsheloInstanceVO(
        MotsheloInstance source,
        MotsheloInstanceVO target)
    {
        // TODO verify behavior of toMotsheloInstanceVO
        super.toMotsheloInstanceVO(source, target);
        // WARNING! No conversion for target.motshelo (can't convert source.getMotshelo():com.systemsjr.motshelo.Motshelo to com.systemsjr.motshelo.vo.MotsheloVO
        // WARNING! No conversion for target.members (can't convert source.getMembers():com.systemsjr.motshelo.member.Member to com.systemsjr.motshelo.member.vo.MemberVO
        // WARNING! No conversion for target.transactions (can't convert source.getTransactions():com.systemsjr.motshelo.transaction.Transaction to com.systemsjr.motshelo.transaction.vo.TransactionVO
        // WARNING! No conversion for target.loans (can't convert source.getLoans():com.systemsjr.motshelo.loan.Loan to com.systemsjr.motshelo.loan.vo.LoanVO
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MotsheloInstanceVO toMotsheloInstanceVO(final MotsheloInstance entity)
    {
        // TODO verify behavior of toMotsheloInstanceVO
        return super.toMotsheloInstanceVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private MotsheloInstance loadMotsheloInstanceFromMotsheloInstanceVO(MotsheloInstanceVO motsheloInstanceVO)
    {
        // TODO implement loadMotsheloInstanceFromMotsheloInstanceVO
        throw new UnsupportedOperationException("com.systemsjr.motshelo.instance.loadMotsheloInstanceFromMotsheloInstanceVO(MotsheloInstanceVO) not yet implemented.");

        /* A typical implementation looks like this:
        if (motsheloInstanceVO.getId() == null)
        {
            return  MotsheloInstance.Factory.newInstance();
        }
        else
        {
            return this.load(motsheloInstanceVO.getId());
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public MotsheloInstance motsheloInstanceVOToEntity(MotsheloInstanceVO motsheloInstanceVO)
    {
        // TODO verify behavior of motsheloInstanceVOToEntity
        MotsheloInstance entity = this.loadMotsheloInstanceFromMotsheloInstanceVO(motsheloInstanceVO);
        this.motsheloInstanceVOToEntity(motsheloInstanceVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void motsheloInstanceVOToEntity(
        MotsheloInstanceVO source,
        MotsheloInstance target,
        boolean copyIfNull)
    {
        // TODO verify behavior of motsheloInstanceVOToEntity
        super.motsheloInstanceVOToEntity(source, target, copyIfNull);
    }

	@Override
	protected Collection<MotsheloInstance> handleFindByInstanceName(String instanceName) throws Exception {
		// TODO Auto-generated method stub
		return null;
	}
}