// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.instance.web.search;

import java.util.Collection;

import javax.faces.context.FacesContext;

import com.systemsjr.motshelo.instance.vo.MotsheloInstanceSearchCriteria;
import com.systemsjr.motshelo.instance.vo.MotsheloInstanceVO;

/**
 * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController
 */
public class MotsheloInstanceSearchControllerImpl
    extends MotsheloInstanceSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1678213271289874025L;

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#doInitialiseSearchScreen(MotsheloInstanceSearchCriteria searchCriteria)
     */
    @Override
    public void doInitialiseSearchScreen(DoInitialiseSearchScreenForm form)
    {
        MotsheloInstanceSearchCriteria searchCriteria = new MotsheloInstanceSearchCriteria();
        form.setSearchCriteria(searchCriteria);
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#doMotsheloInstanceSearch()
     */
    @Override
    public void doMotsheloInstanceSearch()
    {
    	Collection<MotsheloInstanceVO> vos = getMotsheloInstanceService().searchMetsheloInstances(getSearchMotsheloInstancesSearchForm().getSearchCriteria());
    	getSearchMotsheloInstancesSearchForm().setMotsheloInstances(vos);
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#doMotsheloInstanceEdit(java.lang.Long id, MotsheloInstanceVO motsheloInstanceVO)
     */
    @Override
    public void doMotsheloInstanceEdit(DoMotsheloInstanceEditForm form)
    {
    	getSearchMotsheloInstancesForm().setId(form.getId());
    	try {
			form.setMotsheloInstanceVO(getSelectedMotsheloInstance());
		} catch (Throwable e) {
			e.printStackTrace();
		}
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#doMotsheloInstanceDetails(java.lang.Long id, MotsheloInstanceVO motsheloInstanceVO)
     */
    @Override
    public void doMotsheloInstanceDetails(DoMotsheloInstanceDetailsForm form)
    {
    	getSearchMotsheloInstancesForm().setId(form.getId());
    	try {
			form.setMotsheloInstanceVO(getSelectedMotsheloInstance());
		} catch (Throwable e) {
			e.printStackTrace();
		}
    }

	@Override
	protected MotsheloInstanceVO getSelectedMotsheloInstance() throws Throwable {
		MotsheloInstanceVO motsheloInstanceVO = getMotsheloInstanceService().findById(getSearchMotsheloInstancesForm().getId());
		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("motsheloInstanceVO", motsheloInstanceVO);
		return motsheloInstanceVO;
	}
}