// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.instance.web.search;

import com.systemsjr.motshelo.instance.vo.MotsheloInstanceSearchCriteria;
import com.systemsjr.motshelo.instance.vo.MotsheloInstanceVO;
import java.io.Serializable;
import java.util.Arrays;
import java.util.Collection;
import java.util.Date;

/**
 * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController
 */
public class MotsheloInstanceSearchControllerImpl
    extends MotsheloInstanceSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1678213271289874025L;

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#enterInitialiseSearchScreen(MotsheloInstanceSearchCriteria searchCriteria)
     */
    @Override
    public void enterInitialiseSearchScreen(EnterInitialiseSearchScreenForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#doInitialiseSearchScreen(MotsheloInstanceSearchCriteria searchCriteria)
     */
    @Override
    public void doInitialiseSearchScreen(DoInitialiseSearchScreenForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#exitInitialiseSearchScreen(MotsheloInstanceSearchCriteria searchCriteria)
     */
    @Override
    public void exitInitialiseSearchScreen(ExitInitialiseSearchScreenForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#enterMotsheloInstanceSearch()
     */
    @Override
    public void enterMotsheloInstanceSearch()
    {
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#doMotsheloInstanceSearch()
     */
    @Override
    public void doMotsheloInstanceSearch()
    {
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#exitMotsheloInstanceSearch()
     */
    @Override
    public void exitMotsheloInstanceSearch()
    {
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#enterMotsheloInstanceEdit(java.lang.Long id, MotsheloInstanceVO motsheloInstanceVO)
     */
    @Override
    public void enterMotsheloInstanceEdit(EnterMotsheloInstanceEditForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#doMotsheloInstanceEdit(java.lang.Long id, MotsheloInstanceVO motsheloInstanceVO)
     */
    @Override
    public void doMotsheloInstanceEdit(DoMotsheloInstanceEditForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#exitMotsheloInstanceEdit(java.lang.Long id, MotsheloInstanceVO motsheloInstanceVO)
     */
    @Override
    public void exitMotsheloInstanceEdit(ExitMotsheloInstanceEditForm form)
    {
       
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#enterMotsheloInstanceDetails(java.lang.Long id, MotsheloInstanceVO motsheloInstanceVO)
     */
    @Override
    public void enterMotsheloInstanceDetails(EnterMotsheloInstanceDetailsForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#doMotsheloInstanceDetails(java.lang.Long id, MotsheloInstanceVO motsheloInstanceVO)
     */
    @Override
    public void doMotsheloInstanceDetails(DoMotsheloInstanceDetailsForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.instance.web.search.MotsheloInstanceSearchController#exitMotsheloInstanceDetails(java.lang.Long id, MotsheloInstanceVO motsheloInstanceVO)
     */
    @Override
    public void exitMotsheloInstanceDetails(ExitMotsheloInstanceDetailsForm form)
    {
        
    }
}