// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.member.web.details;

import com.systemsjr.motshelo.member.vo.MemberVO;

/**
 * @see com.systemsjr.motshelo.member.web.details.MemberDetailsController
 */
public class MemberDetailsControllerImpl
    extends MemberDetailsController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 4920445328801033330L;

    /**
     * @see com.systemsjr.motshelo.member.web.details.MemberDetailsController#doInitialiseDetailsScreen(MemberVO memberVO)
     */
    @Override
    public void doInitialiseDetailsScreen(DoInitialiseDetailsScreenForm form)
    {
        
    }

	@Override
	public void doMemberEdit(DoMemberEditForm form) throws Throwable {
		// TODO Auto-generated method stub
		
	}
}