// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.member.web.details;

import com.systemsjr.motshelo.member.vo.MemberVO;

/**
 * @see com.systemsjr.motshelo.member.web.details.MemberDetailsController
 */
public class MemberDetailsControllerImpl
    extends MemberDetailsController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 4920445328801033330L;

    /**
     * @see com.systemsjr.motshelo.member.web.details.MemberDetailsController#exitInitialiseDetailsScreen(MemberVO memberVO)
     */
    @Override
    public void exitInitialiseDetailsScreen(ExitInitialiseDetailsScreenForm form)
    {
        // populating value with dummy instance
        MemberVO memberVO = new MemberVO();
        memberVO.setId(new Long((long)3355));
        memberVO.setStatus(null);
        memberVO.setUsername(null);
        memberVO.setName(null);
        memberVO.setSurname(null);
        form.setMemberVO(memberVO);
    }

    /**
     * @see com.systemsjr.motshelo.member.web.details.MemberDetailsController#doInitialiseDetailsScreen(MemberVO memberVO)
     */
    @Override
    public void doInitialiseDetailsScreen(DoInitialiseDetailsScreenForm form)
    {
        // populating value with dummy instance
        MemberVO memberVO = new MemberVO();
        memberVO.setId(new Long((long)3355));
        memberVO.setStatus(null);
        memberVO.setUsername(null);
        memberVO.setName(null);
        memberVO.setSurname(null);
        form.setMemberVO(memberVO);
    }

    /**
     * @see com.systemsjr.motshelo.member.web.details.MemberDetailsController#enterInitialiseDetailsScreen(MemberVO memberVO)
     */
    @Override
    public void enterInitialiseDetailsScreen(EnterInitialiseDetailsScreenForm form)
    {
        // populating value with dummy instance
        MemberVO memberVO = new MemberVO();
        memberVO.setId(new Long((long)3355));
        memberVO.setStatus(null);
        memberVO.setUsername(null);
        memberVO.setName(null);
        memberVO.setSurname(null);
        form.setMemberVO(memberVO);
    }

	@Override
	public void enterMemberEdit(EnterMemberEditForm form) throws Throwable {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void doMemberEdit(DoMemberEditForm form) throws Throwable {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void exitMemberEdit(ExitMemberEditForm form) throws Throwable {
		// TODO Auto-generated method stub
		
	}

}