// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.instance.member.web.details;

import com.systemsjr.motshelo.instance.member.vo.InstanceMemberVO;

/**
 * @see com.systemsjr.motshelo.instance.member.web.details.InstanceMemberDetailsController
 */
public class InstanceMemberDetailsControllerImpl
    extends InstanceMemberDetailsController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1616801238277545285L;

    /**
     * @see com.systemsjr.motshelo.instance.member.web.details.InstanceMemberDetailsController#doInitialiseDetailsScreen(InstanceMemberVO instanceMemberVO)
     */
    @Override
    public void doInitialiseDetailsScreen(DoInitialiseDetailsScreenForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.instance.member.web.details.InstanceMemberDetailsController#doInstanceMemberEdit(InstanceMemberVO instanceMemberVO)
     */
    @Override
    public void doInstanceMemberEdit(DoInstanceMemberEditForm form)
    {
        
    }

}