// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.instance.member.web.details;

import com.systemsjr.motshelo.instance.member.vo.InstanceMemberVO;

/**
 * @see com.systemsjr.motshelo.instance.member.web.details.InstanceMemberDetailsController
 */
public class InstanceMemberDetailsControllerImpl
    extends InstanceMemberDetailsController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1616801238277545285L;

    /**
     * @see com.systemsjr.motshelo.instance.member.web.details.InstanceMemberDetailsController#doInitialiseDetailsScreen(InstanceMemberVO instanceMemberVO)
     */
    @Override
    public void doInitialiseDetailsScreen(DoInitialiseDetailsScreenForm form)
    {
        // populating value with dummy instance
        InstanceMemberVO instanceMemberVO = new InstanceMemberVO();
        instanceMemberVO.setId(new Long((long)3355));
        instanceMemberVO.setMember(null);
        instanceMemberVO.setMotsheloInstance(null);
        instanceMemberVO.setBalance(null);
        instanceMemberVO.setLoans(null);
        instanceMemberVO.setTransactions(null);
        form.setInstanceMemberVO(instanceMemberVO);
    }

    /**
     * @see com.systemsjr.motshelo.instance.member.web.details.InstanceMemberDetailsController#doInstanceMemberEdit(InstanceMemberVO instanceMemberVO)
     */
    @Override
    public void doInstanceMemberEdit(DoInstanceMemberEditForm form)
    {
        // populating value with dummy instance
        InstanceMemberVO instanceMemberVO = new InstanceMemberVO();
        instanceMemberVO.setId(new Long((long)3355));
        instanceMemberVO.setMember(null);
        instanceMemberVO.setMotsheloInstance(null);
        instanceMemberVO.setBalance(null);
        instanceMemberVO.setLoans(null);
        instanceMemberVO.setTransactions(null);
        form.setInstanceMemberVO(instanceMemberVO);
    }

}