// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.instance.period.web.search;

import com.systemsjr.motshelo.instance.period.vo.InstancePeriodSearchCriteria;
import com.systemsjr.motshelo.instance.period.vo.InstancePeriodVO;
import java.io.Serializable;
import java.util.Arrays;
import java.util.Collection;
import java.util.Date;

/**
 * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController
 */
public class InstancePeriodSearchControllerImpl
    extends InstancePeriodSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1635377107388539015L;

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#enterInitialiseSearchScreen(InstancePeriodSearchCriteria searchCriteria)
     */
    @Override
    public void enterInitialiseSearchScreen(EnterInitialiseSearchScreenForm form)
    {
        // populating value with dummy instance
        InstancePeriodSearchCriteria searchCriteria = new InstancePeriodSearchCriteria();
        searchCriteria.setDate(new Date());
        form.setSearchCriteria(searchCriteria);
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#doInitialiseSearchScreen(InstancePeriodSearchCriteria searchCriteria)
     */
    @Override
    public void doInitialiseSearchScreen(DoInitialiseSearchScreenForm form)
    {
        // populating value with dummy instance
        InstancePeriodSearchCriteria searchCriteria = new InstancePeriodSearchCriteria();
        searchCriteria.setDate(new Date());
        form.setSearchCriteria(searchCriteria);
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#exitInitialiseSearchScreen(InstancePeriodSearchCriteria searchCriteria)
     */
    @Override
    public void exitInitialiseSearchScreen(ExitInitialiseSearchScreenForm form)
    {
        // populating value with dummy instance
        InstancePeriodSearchCriteria searchCriteria = new InstancePeriodSearchCriteria();
        searchCriteria.setDate(new Date());
        form.setSearchCriteria(searchCriteria);
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#enterInstancePeriodSearch()
     */
    @Override
    public void enterInstancePeriodSearch()
    {
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#doInstancePeriodSearch()
     */
    @Override
    public void doInstancePeriodSearch()
    {
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#exitInstancePeriodSearch()
     */
    @Override
    public void exitInstancePeriodSearch()
    {
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#enterInstancePeriodEdit(java.lang.Long id, InstancePeriodVO instancePeriodVO)
     */
    @Override
    public void enterInstancePeriodEdit(EnterInstancePeriodEditForm form)
    {
        // populating value with dummy instance
        InstancePeriodVO instancePeriodVO = new InstancePeriodVO();
        instancePeriodVO.setStartDate(new Date());
        instancePeriodVO.setEndDate(new Date());
        instancePeriodVO.setLoanByDate(new Date());
        instancePeriodVO.setMotsheloInstance(null);
        form.setInstancePeriodVO(instancePeriodVO);
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#doInstancePeriodEdit(java.lang.Long id, InstancePeriodVO instancePeriodVO)
     */
    @Override
    public void doInstancePeriodEdit(DoInstancePeriodEditForm form)
    {
        // populating value with dummy instance
        InstancePeriodVO instancePeriodVO = new InstancePeriodVO();
        instancePeriodVO.setStartDate(new Date());
        instancePeriodVO.setEndDate(new Date());
        instancePeriodVO.setLoanByDate(new Date());
        instancePeriodVO.setMotsheloInstance(null);
        form.setInstancePeriodVO(instancePeriodVO);
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#exitInstancePeriodEdit(java.lang.Long id, InstancePeriodVO instancePeriodVO)
     */
    @Override
    public void exitInstancePeriodEdit(ExitInstancePeriodEditForm form)
    {
        // populating value with dummy instance
        InstancePeriodVO instancePeriodVO = new InstancePeriodVO();
        instancePeriodVO.setStartDate(new Date());
        instancePeriodVO.setEndDate(new Date());
        instancePeriodVO.setLoanByDate(new Date());
        instancePeriodVO.setMotsheloInstance(null);
        form.setInstancePeriodVO(instancePeriodVO);
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#enterInstancePeriodDetails(java.lang.Long id, InstancePeriodVO instancePeriodVO)
     */
    @Override
    public void enterInstancePeriodDetails(EnterInstancePeriodDetailsForm form)
    {
        // populating value with dummy instance
        InstancePeriodVO instancePeriodVO = new InstancePeriodVO();
        instancePeriodVO.setStartDate(new Date());
        instancePeriodVO.setEndDate(new Date());
        instancePeriodVO.setLoanByDate(new Date());
        instancePeriodVO.setMotsheloInstance(null);
        form.setInstancePeriodVO(instancePeriodVO);
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#doInstancePeriodDetails(java.lang.Long id, InstancePeriodVO instancePeriodVO)
     */
    @Override
    public void doInstancePeriodDetails(DoInstancePeriodDetailsForm form)
    {
        // populating value with dummy instance
        InstancePeriodVO instancePeriodVO = new InstancePeriodVO();
        instancePeriodVO.setStartDate(new Date());
        instancePeriodVO.setEndDate(new Date());
        instancePeriodVO.setLoanByDate(new Date());
        instancePeriodVO.setMotsheloInstance(null);
        form.setInstancePeriodVO(instancePeriodVO);
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#exitInstancePeriodDetails(java.lang.Long id, InstancePeriodVO instancePeriodVO)
     */
    @Override
    public void exitInstancePeriodDetails(ExitInstancePeriodDetailsForm form)
    {
        // populating value with dummy instance
        InstancePeriodVO instancePeriodVO = new InstancePeriodVO();
        instancePeriodVO.setStartDate(new Date());
        instancePeriodVO.setEndDate(new Date());
        instancePeriodVO.setLoanByDate(new Date());
        instancePeriodVO.setMotsheloInstance(null);
        form.setInstancePeriodVO(instancePeriodVO);
    }

    /**
     * This dummy variable is used to populate the "instancePeriods" table.
     * You may delete it when you add you own code in this controller.
     */
    private static final Collection instancePeriods =
        Arrays.asList(new Object[] {
            "value-1",
            "value-2",
            "value-3",
            "value-4",
            "value-5",
            "value-6",
            "value-7",
            "value-8",
            "value-9",
            "value-10",
            "value-11",
            "value-12",
            "value-13",
            "value-14",
            "value-15",
            "value-16",
            "value-17",
            "value-18",
            "value-19",
            "value-20"
        });

    /**
     * This inner class is used in the dummy implementation in order to get the web application
     * running without any manual programming.
     * You may delete this class when you add you own code in this controller.
     */
    public static final class InstancePeriods implements Serializable
    {

        public InstancePeriods()
        {
        }

    }
}