// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.instance.period.web.search;

import java.util.ArrayList;
import java.util.Collection;

import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;

import com.systemsjr.motshelo.instance.period.vo.InstancePeriodSearchCriteria;
import com.systemsjr.motshelo.instance.period.vo.InstancePeriodVO;
import com.systemsjr.motshelo.instance.vo.MotsheloInstanceVO;

/**
 * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController
 */
public class InstancePeriodSearchControllerImpl
    extends InstancePeriodSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1635377107388539015L;

    
    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#doInitialiseSearchScreen(InstancePeriodSearchCriteria searchCriteria)
     */
    @Override
    public void doInitialiseSearchScreen(DoInitialiseSearchScreenForm form)
    {
    	Collection<MotsheloInstanceVO> motsheloInstances = getMotsheloInstanceService().getAllMotsheloInstances();
    	Collection<SelectItem> instancesBackingList = new ArrayList<SelectItem>();
    	for(MotsheloInstanceVO instance : motsheloInstances)
    	{
    		instancesBackingList.add(new SelectItem(instance.getId(), instance.getInstanceName()));
    	}
    	form.setSearchCriteriaMotsheloInstanceBackingList(instancesBackingList);
    	getSearchInstancePeriodsSearchForm().setSearchCriteriaMotsheloInstanceBackingList(instancesBackingList);
    	
        InstancePeriodSearchCriteria searchCriteria = new InstancePeriodSearchCriteria();
        searchCriteria.setMotsheloInstance(new MotsheloInstanceVO());
        form.setSearchCriteria(searchCriteria);
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#doInstancePeriodSearch()
     */
    @Override
    public void doInstancePeriodSearch()
    {
    	InstancePeriodSearchCriteria searchCriteria = getSearchInstancePeriodsSearchForm().getSearchCriteria();
    	searchCriteria.setMotsheloInstance(getMotsheloInstanceService().findById(searchCriteria.getMotsheloInstance().getId()));
    	Collection<InstancePeriodVO> periods = getInstancePeriodService().searchInstancePeriods(searchCriteria);
    	getSearchInstancePeriodsSearchForm().setInstancePeriods(periods);
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#doInstancePeriodEdit(java.lang.Long id, InstancePeriodVO instancePeriodVO)
     */
    @Override
    public void doInstancePeriodEdit(DoInstancePeriodEditForm form)
    {
    	getSearchInstancePeriodsForm().setId(form.getId());
    	try {
			form.setInstancePeriodVO(getSelectedInstancePeriod());
		} catch (Throwable e) {
			e.printStackTrace();
		}
    }   

    /**
     * @see com.systemsjr.motshelo.instance.period.web.search.InstancePeriodSearchController#doInstancePeriodDetails(java.lang.Long id, InstancePeriodVO instancePeriodVO)
     */
    @Override
    public void doInstancePeriodDetails(DoInstancePeriodDetailsForm form)
    {
    	getSearchInstancePeriodsForm().setId(form.getId());
    	try {
			form.setInstancePeriodVO(getSelectedInstancePeriod());
		} catch (Throwable e) {
			e.printStackTrace();
		}
    }

	@Override
	protected InstancePeriodVO getSelectedInstancePeriod() throws Throwable {
		InstancePeriodVO instancePeriodVO = getInstancePeriodService().findById(getSearchInstancePeriodsForm().getId());
		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("instancePeriodVO", instancePeriodVO);
		return instancePeriodVO;
	}

   
}