// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.instance.period.web.edit;

import java.util.ArrayList;
import java.util.Collection;

import javax.faces.application.FacesMessage;
import javax.faces.application.FacesMessage.Severity;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;

import com.systemsjr.motshelo.instance.period.vo.InstancePeriodSearchCriteria;
import com.systemsjr.motshelo.instance.period.vo.InstancePeriodVO;
import com.systemsjr.motshelo.instance.vo.MotsheloInstanceVO;

/**
 * @see com.systemsjr.motshelo.instance.period.web.edit.InstancePeriodEditController
 */
public class InstancePeriodEditControllerImpl
    extends InstancePeriodEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -6115851754854078696L;

    

    /**
     * @see com.systemsjr.motshelo.instance.period.web.edit.InstancePeriodEditController#doSaveInstancePeriod()
     */
    @Override
    public void doSaveInstancePeriod()
    {
    	InstancePeriodVO instancePeriodVO = getEditInstancePeriodSaveForm().getInstancePeriodVO();
    	instancePeriodVO.setMotsheloInstance(instancePeriodVO.getMotsheloInstance());
    	instancePeriodVO.setPeriodName("-");
    	instancePeriodVO = getInstancePeriodService().saveInstancePeriod(instancePeriodVO);
    	
    	Severity severity = FacesMessage.SEVERITY_INFO;
    	String summary = "SUCCESS: ";
    	String details = "Motshelo instance period saved.";
    	if(instancePeriodVO.getId() == null)
    	{
    		severity = FacesMessage.SEVERITY_ERROR;
        	summary = "ERROR: ";
        	details = "Motshelo instance period could not be saved.";
    	}
    	FacesContext.getCurrentInstance().addMessage("messages", new FacesMessage(severity, summary, details));
    	
    	getEditInstancePeriodSaveForm().setInstancePeriodVO(instancePeriodVO);
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("instancePeriodVO", getEditInstancePeriodSaveForm().getInstancePeriodVO());
    }


    /**
     * @see com.systemsjr.motshelo.instance.period.web.edit.InstancePeriodEditController#doNewInstancePeriod()
     */
    @Override
    public void doNewInstancePeriod()
    {
    	InstancePeriodVO instancePeriodVO = new InstancePeriodVO();
    	getEditInstancePeriodForm().setInstancePeriodVO(instancePeriodVO);
    	getEditInstancePeriodSaveForm().setInstancePeriodVO(instancePeriodVO);
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.edit.InstancePeriodEditController#doInitialiseEditScreen(InstancePeriodVO instancePeriodVO)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
    	Collection<MotsheloInstanceVO> motsheloInstances = getMotsheloInstanceService().getAllMotsheloInstances();
    	Collection<SelectItem> instancesBackingList = new ArrayList<SelectItem>();
    	for(MotsheloInstanceVO instance : motsheloInstances)
    	{
    		instancesBackingList.add(new SelectItem(instance.getId(), instance.getInstanceName()));
    	}
    	form.setInstancePeriodVOMotsheloInstanceBackingList(instancesBackingList);
    	getEditInstancePeriodSaveForm().setInstancePeriodVOMotsheloInstanceBackingList(instancesBackingList);
    	
    	InstancePeriodVO instancePeriodVO = (InstancePeriodVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("instancePeriodVO");
        if(instancePeriodVO == null) {
        	instancePeriodVO = new InstancePeriodVO();
        }
        
        if(instancePeriodVO.getMotsheloInstance() == null)
        {
        	instancePeriodVO.setMotsheloInstance(new MotsheloInstanceVO());
        }
        
        if(instancePeriodVO.getPreviousPeriod() == null)
        {
        	instancePeriodVO.setPreviousPeriod(new InstancePeriodVO());
        }
        
        if(instancePeriodVO.getNextPeriod() == null)
        {
        	instancePeriodVO.setNextPeriod(new InstancePeriodVO());
        }
        
        form.setInstancePeriodVO(instancePeriodVO);        
        MotsheloInstanceVO instanceVO = instancePeriodVO.getMotsheloInstance();
        
        Collection<SelectItem> nextBackingList = new ArrayList<SelectItem>();
        Collection<SelectItem> previousBackingList = new ArrayList<SelectItem>();
        
        if(instanceVO != null && instanceVO.getId() != null) {
        	InstancePeriodSearchCriteria criteria = new InstancePeriodSearchCriteria();
        	criteria.setMotsheloInstance(instanceVO);
        	Collection<InstancePeriodVO> periods = getInstancePeriodService().searchInstancePeriods(criteria);
        	
	        for(InstancePeriodVO period : periods)
	        {
	        	nextBackingList.add(new SelectItem(period.getId(), period.getPeriodName()));
	        	previousBackingList.add(new SelectItem(period.getId(), period.getPeriodName()));
	        }
        }
        
        form.setInstancePeriodVONextPeriodBackingList(nextBackingList);
        getEditInstancePeriodSaveForm().setInstancePeriodVONextPeriodBackingList(nextBackingList);
        form.setInstancePeriodVOPreviousPeriodBackingList(previousBackingList);
        getEditInstancePeriodSaveForm().setInstancePeriodVOPreviousPeriodBackingList(previousBackingList);
    }

}