// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.instance.period.web.edit;

import com.systemsjr.motshelo.instance.period.vo.InstancePeriodVO;
import java.util.Date;

import javax.faces.context.FacesContext;

/**
 * @see com.systemsjr.motshelo.instance.period.web.edit.InstancePeriodEditController
 */
public class InstancePeriodEditControllerImpl
    extends InstancePeriodEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -6115851754854078696L;

    /**
     * @see com.systemsjr.motshelo.instance.period.web.edit.InstancePeriodEditController#enterSaveInstancePeriod()
     */
    @Override
    public void enterSaveInstancePeriod()
    {
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.edit.InstancePeriodEditController#doSaveInstancePeriod()
     */
    @Override
    public void doSaveInstancePeriod()
    {
    	InstancePeriodVO instancePeriodVO = getEditInstancePeriodSaveForm().getInstancePeriodVO();
    	instancePeriodVO = getInstancePeriodService().saveInstancePeriod(instancePeriodVO);
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.edit.InstancePeriodEditController#exitSaveInstancePeriod()
     */
    @Override
    public void exitSaveInstancePeriod()
    {
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("instancePeriodVO", getEditInstancePeriodSaveForm().getInstancePeriodVO());
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.edit.InstancePeriodEditController#exitNewInstancePeriod()
     */
    @Override
    public void exitNewInstancePeriod()
    {
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.edit.InstancePeriodEditController#doNewInstancePeriod()
     */
    @Override
    public void doNewInstancePeriod()
    {
    	InstancePeriodVO instancePeriodVO = new InstancePeriodVO();
    	getEditInstancePeriodForm().setInstancePeriodVO(instancePeriodVO);
    	getEditInstancePeriodSaveForm().setInstancePeriodVO(instancePeriodVO);
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.edit.InstancePeriodEditController#enterNewInstancePeriod()
     */
    @Override
    public void enterNewInstancePeriod()
    {
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.edit.InstancePeriodEditController#exitInitialiseEditScreen(InstancePeriodVO instancePeriodVO)
     */
    @Override
    public void exitInitialiseEditScreen(ExitInitialiseEditScreenForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.edit.InstancePeriodEditController#doInitialiseEditScreen(InstancePeriodVO instancePeriodVO)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
        form.setInstancePeriodVO(getEditInstancePeriodForm().getInstancePeriodVO());
    }

    /**
     * @see com.systemsjr.motshelo.instance.period.web.edit.InstancePeriodEditController#enterInitialiseEditScreen(InstancePeriodVO instancePeriodVO)
     */
    @Override
    public void enterInitialiseEditScreen(EnterInitialiseEditScreenForm form)
    {
        InstancePeriodVO instancePeriodVO = (InstancePeriodVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("instancePeriodVO");
        getEditInstancePeriodSaveForm().setInstancePeriodVO(instancePeriodVO);
        getEditInstancePeriodForm().setInstancePeriodVO(instancePeriodVO);
    }

}