// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.member.web.edit;

import javax.faces.context.FacesContext;

import com.systemsjr.motshelo.member.vo.MemberVO;

/**
 * @see com.systemsjr.motshelo.member.web.edit.MemberEditController
 */
public class MemberEditControllerImpl
    extends MemberEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 6784385525062415648L;

    /**
     * @see com.systemsjr.motshelo.member.web.edit.MemberEditController#enterSaveMember()
     */
    @Override
    public void enterSaveMember()
    {
    }

    /**
     * @see com.systemsjr.motshelo.member.web.edit.MemberEditController#doSaveMember()
     */
    @Override
    public void doSaveMember()
    {
    	MemberVO memberVO = getEditMemberSaveForm().getMemberVO();
    	memberVO = getMemberService().saveMember(memberVO);
    	getEditMemberSaveForm().setMemberVO(memberVO);
    }

    /**
     * @see com.systemsjr.motshelo.member.web.edit.MemberEditController#exitSaveMember()
     */
    @Override
    public void exitSaveMember()
    {
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("memberVO", getEditMemberSaveForm().getMemberVO());
    }

    /**
     * @see com.systemsjr.motshelo.member.web.edit.MemberEditController#exitNewMember()
     */
    @Override
    public void exitNewMember()
    {
    }

    /**
     * @see com.systemsjr.motshelo.member.web.edit.MemberEditController#doNewMember()
     */
    @Override
    public void doNewMember()
    {
    	MemberVO memberVO = new MemberVO();
    	getEditMemberForm().setMemberVO(memberVO);
    	getEditMemberSaveForm().setMemberVO(memberVO);
    }

    /**
     * @see com.systemsjr.motshelo.member.web.edit.MemberEditController#enterNewMember()
     */
    @Override
    public void enterNewMember()
    {
    }

    /**
     * @see com.systemsjr.motshelo.member.web.edit.MemberEditController#exitInitialiseEditScreen(MemberVO memberVO)
     */
    @Override
    public void exitInitialiseEditScreen(ExitInitialiseEditScreenForm form)
    {
    	
    }

    /**
     * @see com.systemsjr.motshelo.member.web.edit.MemberEditController#doInitialiseEditScreen(MemberVO memberVO)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
        form.setMemberVO(getEditMemberForm().getMemberVO());
        getEditMemberSaveForm().setMemberVO(getEditMemberForm().getMemberVO());
    }

    /**
     * @see com.systemsjr.motshelo.member.web.edit.MemberEditController#enterInitialiseEditScreen(MemberVO memberVO)
     */
    @Override
    public void enterInitialiseEditScreen(EnterInitialiseEditScreenForm form)
    {
        MemberVO memberVO = (MemberVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("memberVO");
        getEditMemberForm().setMemberVO(memberVO);
    }

}