// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.member.web.edit;

import javax.faces.application.FacesMessage;
import javax.faces.application.FacesMessage.Severity;
import javax.faces.context.FacesContext;

import com.systemsjr.motshelo.member.vo.MemberVO;

/**
 * @see com.systemsjr.motshelo.member.web.edit.MemberEditController
 */
public class MemberEditControllerImpl
    extends MemberEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 6784385525062415648L;

    /**
     * @see com.systemsjr.motshelo.member.web.edit.MemberEditController#doSaveMember()
     */
    @Override
    public void doSaveMember()
    {
    	MemberVO memberVO = getEditMemberSaveForm().getMemberVO();
    	memberVO = getMemberService().saveMember(memberVO);
    	getEditMemberSaveForm().setMemberVO(memberVO);

    	Severity severity = FacesMessage.SEVERITY_INFO;
    	String summary = "SUCCESS: ";
    	String details = "Member saved.";
    	if(memberVO.getId() == null)
    	{
    		severity = FacesMessage.SEVERITY_ERROR;
        	summary = "ERROR: ";
        	details = "Member could not be saved.";
    	}
    	FacesContext.getCurrentInstance().addMessage("messages", new FacesMessage(severity, summary, details));
    	
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("memberVO", memberVO);
    }

    /**
     * @see com.systemsjr.motshelo.member.web.edit.MemberEditController#doNewMember()
     */
    @Override
    public void doNewMember()
    {
    	MemberVO memberVO = new MemberVO();
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("memberVO", memberVO);
    }

    /**
     * @see com.systemsjr.motshelo.member.web.edit.MemberEditController#doInitialiseEditScreen(MemberVO memberVO)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
    	MemberVO memberVO = (MemberVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("memberVO");
        form.setMemberVO(memberVO);
        getEditMemberSaveForm().setMemberVO(memberVO);
    }

}