// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on 12/04/2018 18:18:01+0200.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.systemsjr.motshelo.member;

import com.systemsjr.motshelo.member.vo.MemberVO;
import org.springframework.stereotype.Repository;

/**
 * @see Member
 */
@Repository
public class MemberDaoImpl
    extends MemberDaoBase
{
    /**
     * {@inheritDoc}
     */
    @Override
    public void toMemberVO(
        Member source,
        MemberVO target)
    {
        // TODO verify behavior of toMemberVO
        super.toMemberVO(source, target);
        // WARNING! No conversion for target.transactions (can't convert source.getTransactions():com.systemsjr.motshelo.transaction.Transaction to java.util.Collection
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MemberVO toMemberVO(final Member entity)
    {
        // TODO verify behavior of toMemberVO
        return super.toMemberVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Member loadMemberFromMemberVO(MemberVO memberVO)
    {
        // TODO implement loadMemberFromMemberVO
        throw new UnsupportedOperationException("com.systemsjr.motshelo.member.loadMemberFromMemberVO(MemberVO) not yet implemented.");

        /* A typical implementation looks like this:
        if (memberVO.getId() == null)
        {
            return  Member.Factory.newInstance();
        }
        else
        {
            return this.load(memberVO.getId());
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public Member memberVOToEntity(MemberVO memberVO)
    {
        // TODO verify behavior of memberVOToEntity
        Member entity = this.loadMemberFromMemberVO(memberVO);
        this.memberVOToEntity(memberVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void memberVOToEntity(
        MemberVO source,
        Member target,
        boolean copyIfNull)
    {
        // TODO verify behavior of memberVOToEntity
        super.memberVOToEntity(source, target, copyIfNull);
    }
}