// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 * Generated by hibernate/HibernateEntityImpl.vsl in andromda-hibernate-cartridge on 12/06/2018 18:00:14+0200.
 */
package com.systemsjr.motshelo.loan;

import com.systemsjr.motshelo.loan.vo.LoanSearchCriteria;
import java.util.List;

/**
 * @see Loan
 */
// HibernateEntityImpl.vsl annotations merge-point
public class LoanImpl
    extends Loan
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -4715948333676993133L;

    /**
     * @see Loan#findByCriteria(LoanSearchCriteria)
     */
    @Override
    public List findByCriteria(LoanSearchCriteria searchCriteria)
    {
        // TODO implement public List findByCriteria(LoanSearchCriteria searchCriteria)
        List rtn = null;
        return rtn;
    }

// HibernateEntityImpl.vsl merge-point
}