// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on 12/10/2018 08:47:25+0200.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.systemsjr.motshelo.loan;

import com.systemsjr.motshelo.loan.vo.LoanSearchCriteria;
import com.systemsjr.motshelo.loan.vo.LoanVO;

import java.util.List;

import org.springframework.stereotype.Repository;

/**
 * @see Loan
 */
@Repository
public class LoanDaoImpl
    extends LoanDaoBase
{
    /**
     * {@inheritDoc}
     */
    @Override
    public void toLoanVO(
        Loan source,
        LoanVO target)
    {
        // TODO verify behavior of toLoanVO
        super.toLoanVO(source, target);
        // WARNING! No conversion for target.member (can't convert source.getMember():com.systemsjr.motshelo.member.Member to com.systemsjr.motshelo.member.vo.MemberVO
        // WARNING! No conversion for target.motshelo (can't convert source.getMotshelo():com.systemsjr.motshelo.Motshelo to com.systemsjr.motshelo.vo.MotsheloVO
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoanVO toLoanVO(final Loan entity)
    {
        // TODO verify behavior of toLoanVO
        return super.toLoanVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Loan loadLoanFromLoanVO(LoanVO loanVO)
    {
        // TODO implement loadLoanFromLoanVO
        throw new UnsupportedOperationException("com.systemsjr.motshelo.loan.loadLoanFromLoanVO(LoanVO) not yet implemented.");

        /* A typical implementation looks like this:
        if (loanVO.getId() == null)
        {
            return  Loan.Factory.newInstance();
        }
        else
        {
            return this.load(loanVO.getId());
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public Loan loanVOToEntity(LoanVO loanVO)
    {
        // TODO verify behavior of loanVOToEntity
        Loan entity = this.loadLoanFromLoanVO(loanVO);
        this.loanVOToEntity(loanVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void loanVOToEntity(
        LoanVO source,
        Loan target,
        boolean copyIfNull)
    {
        // TODO verify behavior of loanVOToEntity
        super.loanVOToEntity(source, target, copyIfNull);
    }

	@Override
	protected List<?> handleFindByCriteria(LoanSearchCriteria searchCriteria) throws Exception {
		// TODO Auto-generated method stub
		return null;
	}
}