// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.member.web.search;

import com.systemsjr.motshelo.member.vo.MemberSearchCriteria;
import com.systemsjr.motshelo.member.vo.MemberVO;
import java.io.Serializable;
import java.util.Arrays;
import java.util.Collection;

import javax.faces.context.FacesContext;

/**
 * @see com.systemsjr.motshelo.member.web.search.MemberSearchController
 */
public class MemberSearchControllerImpl
    extends MemberSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8965989882708466310L;

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#enterInitialiseSearchScreen(MemberSearchCriteria searchCriteria)
     */
    @Override
    public void enterInitialiseSearchScreen(EnterInitialiseSearchScreenForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#doInitialiseSearchScreen(MemberSearchCriteria searchCriteria)
     */
    @Override
    public void doInitialiseSearchScreen(DoInitialiseSearchScreenForm form)
    {
        MemberSearchCriteria criteria = new MemberSearchCriteria();
        form.setSearchCriteria(criteria);
    }

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#exitInitialiseSearchScreen(MemberSearchCriteria searchCriteria)
     */
    @Override
    public void exitInitialiseSearchScreen(ExitInitialiseSearchScreenForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#enterMemberSearch()
     */
    @Override
    public void enterMemberSearch()
    {
    }

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#doMemberSearch()
     */
    @Override
    public void doMemberSearch()
    {
    	Collection<MemberVO> members = getMemberService().searchMembers(getSearchMembersSearchForm().getSearchCriteria());
    	getSearchMembersForm().setMembers(members);
    	getSearchMembersSearchForm().setMembers(members);
    }

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#exitMemberSearch()
     */
    @Override
    public void exitMemberSearch()
    {
    }

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#enterMemberEdit(java.lang.Long id, MemberVO memberVO)
     */
    @Override
    public void enterMemberEdit(EnterMemberEditForm form)
    {
    	MemberVO memberVO = (MemberVO) FacesContext.getCurrentInstance().getExternalContext().getRequestMap().get("row");
    	getSearchMembersEditForm().setMemberVO(memberVO);
    }

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#doMemberEdit(java.lang.Long id, MemberVO memberVO)
     */
    @Override
    public void doMemberEdit(DoMemberEditForm form)
    {
    	MemberVO memberVO = getSearchMembersEditForm().getMemberVO();
    	
    	if(memberVO != null && memberVO.getId() != null)
    	{
    		memberVO = getMemberService().findById(memberVO.getId());
    		form.setMemberVO(memberVO);
    		getSearchMembersEditForm().setMemberVO(memberVO);
    	}
    }

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#exitMemberEdit(java.lang.Long id, MemberVO memberVO)
     */
    @Override
    public void exitMemberEdit(ExitMemberEditForm form)
    {
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("memberVO", getSearchMembersEditForm().getMemberVO());
    }

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#enterMemberDetails(java.lang.Long id, MemberVO memberVO)
     */
    @Override
    public void enterMemberDetails(EnterMemberDetailsForm form)
    {
    	MemberVO memberVO = (MemberVO) FacesContext.getCurrentInstance().getExternalContext().getRequestMap().get("row");
    	getSearchMembersDetailsForm().setMemberVO(memberVO);
    }

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#doMemberDetails(java.lang.Long id, MemberVO memberVO)
     */
    @Override
    public void doMemberDetails(DoMemberDetailsForm form)
    {
    	MemberVO memberVO = getSearchMembersDetailsForm().getMemberVO();
    	
    	if(memberVO != null && memberVO.getId() != null)
    	{
    		memberVO = getMemberService().findById(memberVO.getId());
    		form.setMemberVO(memberVO);
    		getSearchMembersDetailsForm().setMemberVO(memberVO);
    	}
    }

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#exitMemberDetails(java.lang.Long id, MemberVO memberVO)
     */
    @Override
    public void exitMemberDetails(ExitMemberDetailsForm form)
    {
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("memberVO", getSearchMembersDetailsForm().getMemberVO());
    }
}