// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.member.web.search;

import java.util.Collection;

import javax.faces.context.FacesContext;

import com.systemsjr.motshelo.member.vo.MemberSearchCriteria;
import com.systemsjr.motshelo.member.vo.MemberVO;

/**
 * @see com.systemsjr.motshelo.member.web.search.MemberSearchController
 */
public class MemberSearchControllerImpl
    extends MemberSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8965989882708466310L;

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#doInitialiseSearchScreen(MemberSearchCriteria searchCriteria)
     */
    @Override
    public void doInitialiseSearchScreen(DoInitialiseSearchScreenForm form)
    {
        MemberSearchCriteria criteria = new MemberSearchCriteria();
        form.setSearchCriteria(criteria);
    }
    
    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#doMemberSearch()
     */
    @Override
    public void doMemberSearch()
    {
    	Collection<MemberVO> members = getMemberService().searchMembers(getSearchMembersSearchForm().getSearchCriteria());
    	//getSearchMembersForm().setMembers(members);
    	getSearchMembersSearchForm().setMembers(members);
    }

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#doMemberEdit(java.lang.Long id, MemberVO memberVO)
     */
    @Override
    public void doMemberEdit(DoMemberEditForm form)
    {
    	MemberVO memberVO = (MemberVO) FacesContext.getCurrentInstance().getExternalContext().getRequestMap().get("row");
    	
    	if(memberVO != null && memberVO.getId() != null)
    	{
    		memberVO = getMemberService().findById(memberVO.getId());
    		form.setMemberVO(memberVO);
    		getSearchMembersEditForm().setMemberVO(memberVO);
    	}
    	
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("memberVO", memberVO);
    }

    /**
     * @see com.systemsjr.motshelo.member.web.search.MemberSearchController#doMemberDetails(java.lang.Long id, MemberVO memberVO)
     */
    @Override
    public void doMemberDetails(DoMemberDetailsForm form)
    {
    	MemberVO memberVO = (MemberVO) FacesContext.getCurrentInstance().getExternalContext().getRequestMap().get("row");
    	
    	if(memberVO != null && memberVO.getId() != null)
    	{
    		memberVO = getMemberService().findById(memberVO.getId());
    		form.setMemberVO(memberVO);
    		getSearchMembersDetailsForm().setMemberVO(memberVO);
    	}
    	
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("memberVO", getSearchMembersDetailsForm().getMemberVO());
    }

	@Override
	protected MemberVO getSelectedMember() throws Throwable {
		// TODO Auto-generated method stub
		return null;
	}
}