// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.web.search;

import com.systemsjr.motshelo.vo.MotsheloSearchCriteria;
import java.io.Serializable;
import java.util.Arrays;
import java.util.Collection;

/**
 * @see com.systemsjr.motshelo.web.search.MotsheloSearchController
 */
public class MotsheloSearchControllerImpl
    extends MotsheloSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 6787903515150980938L;

    /**
     * @see com.systemsjr.motshelo.web.search.MotsheloSearchController#initialiseSearchScreen(MotsheloSearchCriteria searchCriteria)
     */
    @Override
    public void initialiseSearchScreen(InitialiseSearchScreenForm form)
    {
        // populating value with dummy instance
        MotsheloSearchCriteria searchCriteria = new MotsheloSearchCriteria();
        searchCriteria.setYear(new Integer((int)3704893));
        searchCriteria.setName(null);
        form.setSearchCriteria(searchCriteria);
    }

    /**
     * This dummy variable is used to populate the "motsheloLists" table.
     * You may delete it when you add you own code in this controller.
     */
    private static final Collection motsheloLists =
        Arrays.asList(new Object[] {
            new MotsheloLists("id-1", "name-1", "year-1", "balance-1"),
            new MotsheloLists("id-2", "name-2", "year-2", "balance-2"),
            new MotsheloLists("id-3", "name-3", "year-3", "balance-3"),
            new MotsheloLists("id-4", "name-4", "year-4", "balance-4"),
            new MotsheloLists("id-5", "name-5", "year-5", "balance-5"),
            new MotsheloLists("id-6", "name-6", "year-6", "balance-6"),
            new MotsheloLists("id-7", "name-7", "year-7", "balance-7"),
            new MotsheloLists("id-8", "name-8", "year-8", "balance-8"),
            new MotsheloLists("id-9", "name-9", "year-9", "balance-9"),
            new MotsheloLists("id-10", "name-10", "year-10", "balance-10"),
            new MotsheloLists("id-11", "name-11", "year-11", "balance-11"),
            new MotsheloLists("id-12", "name-12", "year-12", "balance-12"),
            new MotsheloLists("id-13", "name-13", "year-13", "balance-13"),
            new MotsheloLists("id-14", "name-14", "year-14", "balance-14"),
            new MotsheloLists("id-15", "name-15", "year-15", "balance-15"),
            new MotsheloLists("id-16", "name-16", "year-16", "balance-16"),
            new MotsheloLists("id-17", "name-17", "year-17", "balance-17"),
            new MotsheloLists("id-18", "name-18", "year-18", "balance-18"),
            new MotsheloLists("id-19", "name-19", "year-19", "balance-19"),
            new MotsheloLists("id-20", "name-20", "year-20", "balance-20")
        });

    /**
     * This inner class is used in the dummy implementation in order to get the web application
     * running without any manual programming.
     * You may delete this class when you add you own code in this controller.
     */
    public static final class MotsheloLists implements Serializable
    {
        private String id = null;
        private String name = null;
        private String year = null;
        private String balance = null;

        public MotsheloLists(String id, String name, String year, String balance)
        {
            this.id = id;
            this.name = name;
            this.year = year;
            this.balance = balance;
        }

        public void setId(String id)
        {
            this.id = id;
        }

        public String getId()
        {
            return this.id;
        }

        public void setName(String name)
        {
            this.name = name;
        }

        public String getName()
        {
            return this.name;
        }

        public void setYear(String year)
        {
            this.year = year;
        }

        public String getYear()
        {
            return this.year;
        }

        public void setBalance(String balance)
        {
            this.balance = balance;
        }

        public String getBalance()
        {
            return this.balance;
        }

    }
}