// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.web.search;

import com.systemsjr.motshelo.vo.MotsheloSearchCriteria;
import com.systemsjr.motshelo.vo.MotsheloVO;
import java.io.Serializable;
import java.util.Arrays;
import java.util.Collection;
import java.util.Date;

import javax.faces.context.FacesContext;

/**
 * @see com.systemsjr.motshelo.web.search.MotsheloSearchController
 */
public class MotsheloSearchControllerImpl
    extends MotsheloSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -1974807143693285405L;

    /**
     * @see com.systemsjr.motshelo.web.search.MotsheloSearchController#initialiseSearchScreen(MotsheloSearchCriteria searchCriteria)
     */
    @Override
    public void initialiseSearchScreen(InitialiseSearchScreenForm form)
    {
        // populating value with dummy instance
        MotsheloSearchCriteria searchCriteria = new MotsheloSearchCriteria();
        searchCriteria.setYear(new Integer((int)3704893));
        searchCriteria.setName(null);
        form.setSearchCriteria(searchCriteria);
    }

    /**
     * @see com.systemsjr.motshelo.web.search.MotsheloSearchController#enterMetsheloSearch()
     */
    @Override
    public void enterMetsheloSearch()
    {
    }

    /**
     * @see com.systemsjr.motshelo.web.search.MotsheloSearchController#doMetsheloSearch()
     */
    @Override
    public void doMetsheloSearch()
    {
    	Collection<MotsheloVO> metshelo = getMotsheloService().searchMetshelo(getSearchMetsheloSearchForm().getSearchCriteria());
    	getSearchMetsheloSearchForm().setMotsheloLists(metshelo);
    }

    /**
     * @see com.systemsjr.motshelo.web.search.MotsheloSearchController#exitMetsheloSearch()
     */
    @Override
    public void exitMetsheloSearch()
    {
    }

    /**
     * @see com.systemsjr.motshelo.web.search.MotsheloSearchController#enterEditMotshelo(java.lang.Long id, MotsheloVO motsheloVO)
     */
    @Override
    public void enterEditMotshelo(EnterEditMotsheloForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.web.search.MotsheloSearchController#doEditMotshelo(java.lang.Long id, MotsheloVO motsheloVO)
     */
    @Override
    public void doEditMotshelo(DoEditMotsheloForm form)
    {
    	MotsheloVO motsheloVO = (MotsheloVO) FacesContext.getCurrentInstance().getExternalContext().getRequestMap().get("row");
    	
    	if(motsheloVO != null && motsheloVO.getId() != null)
    	{
    		motsheloVO = getMotsheloService().findById(motsheloVO.getId());
    		form.setMotsheloVO(motsheloVO);
    		this.getSearchMetsheloEditForm().setMotsheloVO(motsheloVO);
    		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("motsheloVO", motsheloVO);
    	}
    }

    /**
     * @see com.systemsjr.motshelo.web.search.MotsheloSearchController#exitEditMotshelo(java.lang.Long id, MotsheloVO motsheloVO)
     */
    @Override
    public void exitEditMotshelo(ExitEditMotsheloForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.web.search.MotsheloSearchController#enterMotsheloDetails(java.lang.Long id, MotsheloVO motsheloVO)
     */
    @Override
    public void enterMotsheloDetails(EnterMotsheloDetailsForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.web.search.MotsheloSearchController#doMotsheloDetails(java.lang.Long id, MotsheloVO motsheloVO)
     */
    @Override
    public void doMotsheloDetails(DoMotsheloDetailsForm form)
    {
    	MotsheloVO motsheloVO = (MotsheloVO) FacesContext.getCurrentInstance().getExternalContext().getRequestMap().get("row");
    	
    	if(motsheloVO != null && motsheloVO.getId() != null)
    	{
    		motsheloVO = getMotsheloService().findById(motsheloVO.getId());
    		form.setMotsheloVO(motsheloVO);
    		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("motsheloVO", motsheloVO);
    	}
    }

    /**
     * @see com.systemsjr.motshelo.web.search.MotsheloSearchController#exitMotsheloDetails(java.lang.Long id, MotsheloVO motsheloVO)
     */
    @Override
    public void exitMotsheloDetails(ExitMotsheloDetailsForm form)
    {
        
    }
}