// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.instance.period.web.details;

import com.systemsjr.motshelo.instance.period.vo.InstancePeriodVO;

/**
 * @see com.systemsjr.motshelo.instance.period.web.details.InstancePeriodDetailsController
 */
public class InstancePeriodDetailsControllerImpl
    extends InstancePeriodDetailsController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5717107477669974309L;

    /**
     * @see com.systemsjr.motshelo.instance.period.web.details.InstancePeriodDetailsController#doInitialiseDetailsScreen(InstancePeriodVO instancePeriodVO)
     */
    @Override
    public void doInitialiseDetailsScreen(DoInitialiseDetailsScreenForm form)
    {
        
    }

   
	@Override
	public void doInstancePeriodEdit(DoInstancePeriodEditForm form) throws Throwable {
		// TODO Auto-generated method stub
		
	}
}