// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.instance.web.details;

import com.systemsjr.motshelo.instance.vo.MotsheloInstanceVO;

/**
 * @see com.systemsjr.motshelo.instance.web.details.MotsheloInstanceDetailsController
 */
public class MotsheloInstanceDetailsControllerImpl
    extends MotsheloInstanceDetailsController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -6586441078799553517L;

    /**
     * @see com.systemsjr.motshelo.instance.web.details.MotsheloInstanceDetailsController#doInitialiseDetailsScreen(MotsheloInstanceVO motsheloInstanceVO)
     */
    @Override
    public void doInitialiseDetailsScreen(DoInitialiseDetailsScreenForm form)
    {
        
    }


    /**
     * @see com.systemsjr.motshelo.instance.web.details.MotsheloInstanceDetailsController#doNextMotsheloInstance()
     */
    @Override
    public void doNextMotsheloInstance()
    {
    }


	@Override
	public void doMotsheloInstanceEdit(DoMotsheloInstanceEditForm form) throws Throwable {
		// TODO Auto-generated method stub
		
	}

}