// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.transaction.web.edit;

import com.systemsjr.motshelo.transaction.vo.TransactionVO;
import java.util.Date;

/**
 * @see com.systemsjr.motshelo.transaction.web.edit.TransactionEditController
 */
public class TransactionEditControllerImpl
    extends TransactionEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1351660648251357502L;

    /**
     * @see com.systemsjr.motshelo.transaction.web.edit.TransactionEditController#doInitialiseEditScreen(TransactionVO transactionVO)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
        // populating value with dummy instance
        TransactionVO transactionVO = new TransactionVO();
        transactionVO.setId(new Long((long)3355));
        transactionVO.setTransactionDate(new Date());
        transactionVO.setTransactionAmount(null);
        transactionVO.setTransactionType(null);
        transactionVO.setTransactionMode(null);
        transactionVO.setInstanceMember(null);
        transactionVO.setMotsheloInstance(null);
        form.setTransactionVO(transactionVO);
    }

    /**
     * @see com.systemsjr.motshelo.transaction.web.edit.TransactionEditController#doNewTransaction()
     */
    @Override
    public void doNewTransaction()
    {
    }

    /**
     * @see com.systemsjr.motshelo.transaction.web.edit.TransactionEditController#doSaveTransaction()
     */
    @Override
    public void doSaveTransaction()
    {
    }

}