// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.web.edit;

import com.systemsjr.motshelo.vo.MotsheloVO;
import java.util.Arrays;
import java.util.Date;

/**
 * @see com.systemsjr.motshelo.web.edit.MotsheloEditController
 */
public class MotsheloEditControllerImpl
    extends MotsheloEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -7273825904286601925L;

    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#enterInitialiseEditScreen(MotsheloVO motsheloVO)
     */
    @Override
    public void enterInitialiseEditScreen(EnterInitialiseEditScreenForm form)
    {
        // populating value with dummy instance
        MotsheloVO motsheloVO = new MotsheloVO();
        motsheloVO.setId(new Long((long)3355));
        motsheloVO.setYear(new Integer((int)3704893));
        motsheloVO.setBalance(null);
        motsheloVO.setMembers(Arrays.asList(new Object[] {"members-1", "members-2", "members-3", "members-4", "members-5"}));
        motsheloVO.setName(null);
        motsheloVO.setLastUpdate(new Date());
        motsheloVO.setLoanDefaultInterest(new Float((float)0));
        motsheloVO.setRepaymentTerm(new Integer((int)-476144769));
        motsheloVO.setLoanInterest(new Float((float)0));
        motsheloVO.setMonthlyContribution(null);
        form.setMotsheloVO(motsheloVO);
    }

    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#doInitialiseEditScreen(MotsheloVO motsheloVO)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
        // populating value with dummy instance
        MotsheloVO motsheloVO = new MotsheloVO();
        motsheloVO.setId(new Long((long)3355));
        motsheloVO.setYear(new Integer((int)3704893));
        motsheloVO.setBalance(null);
        motsheloVO.setMembers(Arrays.asList(new Object[] {"members-1", "members-2", "members-3", "members-4", "members-5"}));
        motsheloVO.setName(null);
        motsheloVO.setLastUpdate(new Date());
        motsheloVO.setLoanDefaultInterest(new Float((float)0));
        motsheloVO.setRepaymentTerm(new Integer((int)-476144769));
        motsheloVO.setLoanInterest(new Float((float)0));
        motsheloVO.setMonthlyContribution(null);
        form.setMotsheloVO(motsheloVO);
    }

    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#exitInitialiseEditScreen(MotsheloVO motsheloVO)
     */
    @Override
    public void exitInitialiseEditScreen(ExitInitialiseEditScreenForm form)
    {
        // populating value with dummy instance
        MotsheloVO motsheloVO = new MotsheloVO();
        motsheloVO.setId(new Long((long)3355));
        motsheloVO.setYear(new Integer((int)3704893));
        motsheloVO.setBalance(null);
        motsheloVO.setMembers(Arrays.asList(new Object[] {"members-1", "members-2", "members-3", "members-4", "members-5"}));
        motsheloVO.setName(null);
        motsheloVO.setLastUpdate(new Date());
        motsheloVO.setLoanDefaultInterest(new Float((float)0));
        motsheloVO.setRepaymentTerm(new Integer((int)-476144769));
        motsheloVO.setLoanInterest(new Float((float)0));
        motsheloVO.setMonthlyContribution(null);
        form.setMotsheloVO(motsheloVO);
    }

    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#enterNewMotshelo()
     */
    @Override
    public void enterNewMotshelo()
    {
    }

    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#doNewMotshelo()
     */
    @Override
    public void doNewMotshelo()
    {
    }

    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#exitNewMotshelo()
     */
    @Override
    public void exitNewMotshelo()
    {
    }

    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#enterSaveMotshelo()
     */
    @Override
    public void enterSaveMotshelo()
    {
    }

    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#doSaveMotshelo()
     */
    @Override
    public void doSaveMotshelo()
    {
    }

    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#exitSaveMotshelo()
     */
    @Override
    public void exitSaveMotshelo()
    {
    }

    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#enterUpdateMotshelo()
     */
    @Override
    public void enterUpdateMotshelo()
    {
    }

    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#doUpdateMotshelo()
     */
    @Override
    public void doUpdateMotshelo()
    {
    }

    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#exitUpdateMotshelo()
     */
    @Override
    public void exitUpdateMotshelo()
    {
    }

}