// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.web.edit;

import java.util.ArrayList;
import java.util.Collection;

import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;

import com.systemsjr.motshelo.member.vo.MemberVO;
import com.systemsjr.motshelo.vo.MotsheloVO;

/**
 * @see com.systemsjr.motshelo.web.edit.MotsheloEditController
 */
public class MotsheloEditControllerImpl
    extends MotsheloEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -7273825904286601925L;

    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#doInitialiseEditScreen(MotsheloVO motsheloVO)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
    	Collection<SelectItem> memberBackingList = new ArrayList<SelectItem>();
    	
    	for(MemberVO member : getMemberService().getAllMembers())
    	{
    		memberBackingList.add(new SelectItem(member.getId(), member.getName() + " " + member.getSurname()));
    	}
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("memberBackingList", memberBackingList);
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("selectedMember", new MemberVO());
    	
    	MotsheloVO motsheloVO = (MotsheloVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("motsheloVO");
        
        if(motsheloVO != null && motsheloVO.getId() != null)
    	{
    		motsheloVO = getMotsheloService().findById(motsheloVO.getId());
    				
    	}
        form.setMotsheloVO(motsheloVO);
		//getEditMotsheloSaveForm().setMotsheloVO(motsheloVO);
    	getEditMotsheloForm().setMotsheloVO(motsheloVO);  
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("motsheloVO", motsheloVO);
    }


    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#doNewMotshelo()
     */
    @Override
    public void doNewMotshelo()
    {
    	MotsheloVO motsheloVO = new MotsheloVO();
    	getEditMotsheloSaveForm().setMotsheloVO(motsheloVO);
    }

    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#doSaveMotshelo()
     */
    @Override
    public void doSaveMotshelo()
    {
    	MotsheloVO motsheloVO = getEditMotsheloSaveForm().getMotsheloVO();
    	
    	//TODO: do the actual saving
    	getMotsheloService().saveMotshelo(motsheloVO);
    	getEditMotsheloSaveForm().setMotsheloVO(motsheloVO);
    	FacesContext.getCurrentInstance().getExternalContext().getFlash().put("motsheloVO", motsheloVO);
    }
    
    /**
     * @see com.systemsjr.motshelo.web.edit.MotsheloEditController#doUpdateMotshelo()
     */
    @Override
    public void doUpdateMotshelo()
    {
    	
    }


	@Override
	public void doAddMember() throws Throwable {
		MemberVO member = (MemberVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("selectedMember");
		member = getMemberService().findById(member.getId());
		getEditMotsheloSaveForm().getMotsheloVO().getMembers().add(member);
	}
}