// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on 12/19/2018 14:18:00+0200.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package com.systemsjr.motshelo.instance.period;

import com.systemsjr.motshelo.instance.period.vo.InstancePeriodSearchCriteria;
import com.systemsjr.motshelo.instance.period.vo.InstancePeriodVO;
import java.util.Collection;
import org.springframework.stereotype.Repository;

/**
 * @see InstancePeriod
 */
@Repository
public class InstancePeriodDaoImpl
    extends InstancePeriodDaoBase
{
    /**
     * {@inheritDoc}
     */
    @Override
    protected Collection<InstancePeriod> handleFindByCriteria(InstancePeriodSearchCriteria searchCriteria)
    {
        // TODO implement public Collection<InstancePeriod> handleFindByCriteria(InstancePeriodSearchCriteria searchCriteria)
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toInstancePeriodVO(
        InstancePeriod source,
        InstancePeriodVO target)
    {
        // TODO verify behavior of toInstancePeriodVO
        super.toInstancePeriodVO(source, target);
        // WARNING! No conversion for target.motsheloInstance (can't convert source.getMotsheloInstance():com.systemsjr.motshelo.instance.MotsheloInstance to com.systemsjr.motshelo.instance.vo.MotsheloInstanceVO
        if(source.getMotsheloInstance() != null)
        {
        	target.setMotsheloInstance(getMotsheloInstanceDao().toMotsheloInstanceVO(source.getMotsheloInstance()));
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InstancePeriodVO toInstancePeriodVO(final InstancePeriod entity)
    {
        // TODO verify behavior of toInstancePeriodVO
        return super.toInstancePeriodVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private InstancePeriod loadInstancePeriodFromInstancePeriodVO(InstancePeriodVO instancePeriodVO)
    {
    	InstancePeriod instancePeriod = InstancePeriod.Factory.newInstance();
        
        if (instancePeriodVO.getId() != null)
        {
            instancePeriod = this.load(instancePeriodVO.getId());
        }
        
        return instancePeriod;
    }

    /**
     * {@inheritDoc}
     */
    public InstancePeriod instancePeriodVOToEntity(InstancePeriodVO instancePeriodVO)
    {
        // TODO verify behavior of instancePeriodVOToEntity
        InstancePeriod entity = this.loadInstancePeriodFromInstancePeriodVO(instancePeriodVO);
        this.instancePeriodVOToEntity(instancePeriodVO, entity, true);
        
        if(instancePeriodVO.getMotsheloInstance() != null)
        {
        	entity.setMotsheloInstance(getMotsheloInstanceDao().load(instancePeriodVO.getMotsheloInstance().getId()));
        }
        
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void instancePeriodVOToEntity(
        InstancePeriodVO source,
        InstancePeriod target,
        boolean copyIfNull)
    {
        // TODO verify behavior of instancePeriodVOToEntity
        super.instancePeriodVOToEntity(source, target, copyIfNull);
    }
}