// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.web.details;

import com.systemsjr.motshelo.vo.MotsheloVO;
import java.util.Arrays;
import java.util.Date;

import javax.faces.context.FacesContext;

/**
 * @see com.systemsjr.motshelo.web.details.MotsheloDetailsController
 */
public class MotsheloDetailsControllerImpl
    extends MotsheloDetailsController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -3221153127722761029L;

    /**
     * @see com.systemsjr.motshelo.web.details.MotsheloDetailsController#enterInitialiseDetailsScreen(MotsheloVO motsheloVO)
     */
    @Override
    public void enterInitialiseDetailsScreen(EnterInitialiseDetailsScreenForm form)
    {
    	MotsheloVO motsheloVO = (MotsheloVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("motsheloVO");
    	form.setMotsheloVO(motsheloVO);
    	getMotsheloDetailsForm().setMotsheloVO(motsheloVO);
    }

    /**
     * @see com.systemsjr.motshelo.web.details.MotsheloDetailsController#doInitialiseDetailsScreen(MotsheloVO motsheloVO)
     */
    @Override
    public void doInitialiseDetailsScreen(DoInitialiseDetailsScreenForm form)
    {
        
    }

    /**
     * @see com.systemsjr.motshelo.web.details.MotsheloDetailsController#exitInitialiseDetailsScreen(MotsheloVO motsheloVO)
     */
    @Override
    public void exitInitialiseDetailsScreen(ExitInitialiseDetailsScreenForm form)
    {
        
    }

	@Override
	public void enterMotsheloEdit(EnterMotsheloEditForm form) throws Throwable {
		// TODO Auto-generated method stub
		getMotsheloEditForm().setMotsheloVO(getMotsheloDetailsForm().getMotsheloVO());
	}

	@Override
	public void doMotsheloEdit(DoMotsheloEditForm form) throws Throwable {
				
	}

	@Override
	public void exitMotsheloEdit(ExitMotsheloEditForm form) throws Throwable {
		// TODO Auto-generated method stub
		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("motsheloVO", getMotsheloEditForm().getMotsheloVO());
	}

}