// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.web.details;

import com.systemsjr.motshelo.vo.MotsheloVO;
import java.util.Arrays;
import java.util.Date;

/**
 * @see com.systemsjr.motshelo.web.details.MotsheloDetailsController
 */
public class MotsheloDetailsControllerImpl
    extends MotsheloDetailsController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -3221153127722761029L;

    /**
     * @see com.systemsjr.motshelo.web.details.MotsheloDetailsController#enterInitialiseDetailsScreen(MotsheloVO motsheloVO)
     */
    @Override
    public void enterInitialiseDetailsScreen(EnterInitialiseDetailsScreenForm form)
    {
        // populating value with dummy instance
        MotsheloVO motsheloVO = new MotsheloVO();
        motsheloVO.setId(new Long((long)3355));
        motsheloVO.setYear(new Integer((int)3704893));
        motsheloVO.setBalance(null);
        motsheloVO.setMembers(Arrays.asList(new Object[] {"members-1", "members-2", "members-3", "members-4", "members-5"}));
        motsheloVO.setName(null);
        motsheloVO.setLastUpdate(new Date());
        motsheloVO.setLoanDefaultInterest(new Float((float)0));
        motsheloVO.setRepaymentTerm(new Integer((int)-476144769));
        motsheloVO.setLoanInterest(new Float((float)0));
        motsheloVO.setMonthlyContribution(null);
        form.setMotsheloVO(motsheloVO);
    }

    /**
     * @see com.systemsjr.motshelo.web.details.MotsheloDetailsController#doInitialiseDetailsScreen(MotsheloVO motsheloVO)
     */
    @Override
    public void doInitialiseDetailsScreen(DoInitialiseDetailsScreenForm form)
    {
        // populating value with dummy instance
        MotsheloVO motsheloVO = new MotsheloVO();
        motsheloVO.setId(new Long((long)3355));
        motsheloVO.setYear(new Integer((int)3704893));
        motsheloVO.setBalance(null);
        motsheloVO.setMembers(Arrays.asList(new Object[] {"members-1", "members-2", "members-3", "members-4", "members-5"}));
        motsheloVO.setName(null);
        motsheloVO.setLastUpdate(new Date());
        motsheloVO.setLoanDefaultInterest(new Float((float)0));
        motsheloVO.setRepaymentTerm(new Integer((int)-476144769));
        motsheloVO.setLoanInterest(new Float((float)0));
        motsheloVO.setMonthlyContribution(null);
        form.setMotsheloVO(motsheloVO);
    }

    /**
     * @see com.systemsjr.motshelo.web.details.MotsheloDetailsController#exitInitialiseDetailsScreen(MotsheloVO motsheloVO)
     */
    @Override
    public void exitInitialiseDetailsScreen(ExitInitialiseDetailsScreenForm form)
    {
        // populating value with dummy instance
        MotsheloVO motsheloVO = new MotsheloVO();
        motsheloVO.setId(new Long((long)3355));
        motsheloVO.setYear(new Integer((int)3704893));
        motsheloVO.setBalance(null);
        motsheloVO.setMembers(Arrays.asList(new Object[] {"members-1", "members-2", "members-3", "members-4", "members-5"}));
        motsheloVO.setName(null);
        motsheloVO.setLastUpdate(new Date());
        motsheloVO.setLoanDefaultInterest(new Float((float)0));
        motsheloVO.setRepaymentTerm(new Integer((int)-476144769));
        motsheloVO.setLoanInterest(new Float((float)0));
        motsheloVO.setMonthlyContribution(null);
        form.setMotsheloVO(motsheloVO);
    }

}