// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.loan.web.edit;

import com.systemsjr.motshelo.loan.vo.LoanVO;
import java.util.Date;

/**
 * @see com.systemsjr.motshelo.loan.web.edit.LoanEditController
 */
public class LoanEditControllerImpl
    extends LoanEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 5482841666824498085L;

    /**
     * @see com.systemsjr.motshelo.loan.web.edit.LoanEditController#enterSaveLoan()
     */
    @Override
    public void enterSaveLoan()
    {
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.edit.LoanEditController#doSaveLoan()
     */
    @Override
    public void doSaveLoan()
    {
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.edit.LoanEditController#exitSaveLoan()
     */
    @Override
    public void exitSaveLoan()
    {
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.edit.LoanEditController#exitNewLoan()
     */
    @Override
    public void exitNewLoan()
    {
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.edit.LoanEditController#doNewLoan()
     */
    @Override
    public void doNewLoan()
    {
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.edit.LoanEditController#enterNewLoan()
     */
    @Override
    public void enterNewLoan()
    {
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.edit.LoanEditController#exitInitialiseEditScreen(LoanVO loanVO)
     */
    @Override
    public void exitInitialiseEditScreen(ExitInitialiseEditScreenForm form)
    {
        // populating value with dummy instance
        LoanVO loanVO = new LoanVO();
        loanVO.setId(new Long((long)3355));
        loanVO.setInstanceMember(null);
        loanVO.setAmount(null);
        loanVO.setStartDate(new Date());
        loanVO.setExpectedEndDate(new Date());
        loanVO.setActualEndDate(new Date());
        loanVO.setBalance(null);
        loanVO.setStatus(null);
        loanVO.setMotsheloInstance(null);
        loanVO.setInterests(null);
        form.setLoanVO(loanVO);
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.edit.LoanEditController#doInitialiseEditScreen(LoanVO loanVO)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
        // populating value with dummy instance
        LoanVO loanVO = new LoanVO();
        loanVO.setId(new Long((long)3355));
        loanVO.setInstanceMember(null);
        loanVO.setAmount(null);
        loanVO.setStartDate(new Date());
        loanVO.setExpectedEndDate(new Date());
        loanVO.setActualEndDate(new Date());
        loanVO.setBalance(null);
        loanVO.setStatus(null);
        loanVO.setMotsheloInstance(null);
        loanVO.setInterests(null);
        form.setLoanVO(loanVO);
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.edit.LoanEditController#enterInitialiseEditScreen(LoanVO loanVO)
     */
    @Override
    public void enterInitialiseEditScreen(EnterInitialiseEditScreenForm form)
    {
        // populating value with dummy instance
        LoanVO loanVO = new LoanVO();
        loanVO.setId(new Long((long)3355));
        loanVO.setInstanceMember(null);
        loanVO.setAmount(null);
        loanVO.setStartDate(new Date());
        loanVO.setExpectedEndDate(new Date());
        loanVO.setActualEndDate(new Date());
        loanVO.setBalance(null);
        loanVO.setStatus(null);
        loanVO.setMotsheloInstance(null);
        loanVO.setInterests(null);
        form.setLoanVO(loanVO);
    }

}