// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package com.systemsjr.motshelo.loan.web.edit;

import java.util.ArrayList;
import java.util.Collection;

import javax.faces.application.FacesMessage;
import javax.faces.application.FacesMessage.Severity;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;

import com.systemsjr.motshelo.instance.member.vo.InstanceMemberVO;
import com.systemsjr.motshelo.instance.vo.MotsheloInstanceVO;
import com.systemsjr.motshelo.loan.vo.LoanVO;

/**
 * @see com.systemsjr.motshelo.loan.web.edit.LoanEditController
 */
public class LoanEditControllerImpl
    extends LoanEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 5482841666824498085L;

    /**
     * @see com.systemsjr.motshelo.loan.web.edit.LoanEditController#doSaveLoan()
     */
    @Override
    public void doSaveLoan()
    {
    	LoanVO loan = getEditLoanSaveForm().getLoanVO();
    	loan.setExpectedEndDate(loan.getStartDate());
    	loan = getLoanService().saveLoan(loan);

    	Severity severity = FacesMessage.SEVERITY_INFO;
    	String summary = "SUCCESS: ";
    	String details = "Loan saved.";
    	if(loan.getId() == null)
    	{
    		severity = FacesMessage.SEVERITY_ERROR;
        	summary = "ERROR: ";
        	details = "Loan could not be saved.";
    	}
    	FacesContext.getCurrentInstance().addMessage("messages", new FacesMessage(severity, summary, details));
    	
    	getEditLoanSaveForm().setLoanVO(loan);
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.edit.LoanEditController#doNewLoan()
     */
    @Override
    public void doNewLoan()
    {
    	LoanVO loan = new LoanVO();
    	getEditLoanSaveForm().setLoanVO(loan);
    }

    /**
     * @see com.systemsjr.motshelo.loan.web.edit.LoanEditController#doInitialiseEditScreen(LoanVO loanVO)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
    	LoanVO loanVO = (LoanVO) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("loanVO");
    	if(loanVO == null)
    	{
    		loanVO = new LoanVO();
    	}
    	
    	if(loanVO.getMotsheloInstance() == null)
    	{
    		loanVO.setMotsheloInstance(new MotsheloInstanceVO());
    	}
    	
    	if(loanVO.getInstanceMember() == null)
    	{
    		loanVO.setInstanceMember(new InstanceMemberVO());
    	}
    	
    	form.setLoanVO(loanVO);
    	getEditLoanSaveForm().setLoanVO(loanVO);
    	
    	Collection<SelectItem> instanceBackingList = new ArrayList<SelectItem>();
    	for(MotsheloInstanceVO insVO : getMotsheloInstanceService().getAllMotsheloInstances())
    	{
    		instanceBackingList.add(new SelectItem(insVO.getId(), insVO.getInstanceName()));
    	}
    	
    	form.setLoanVOMotsheloInstanceBackingList(instanceBackingList);
    	getEditLoanSaveForm().setLoanVOMotsheloInstanceBackingList(instanceBackingList);
    	
    	try {
    		updateEditForm();
		} catch (Throwable e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

	@Override
	public void updateEditForm() throws Throwable {
		Collection<SelectItem> memberBackingList = new ArrayList<SelectItem>();
		if (getEditLoanSaveForm().getLoanVO() != null && getEditLoanSaveForm().getLoanVO().getMotsheloInstance().getId() != null) {
			MotsheloInstanceVO insVO = getMotsheloInstanceService().findById(getEditLoanSaveForm().getLoanVO().getMotsheloInstance().getId());
			for(InstanceMemberVO memVO : insVO.getInstanceMembers())
			{
				memberBackingList.add(new SelectItem(memVO.getId(), memVO.getMember().getName() + " " + memVO.getMember().getSurname()));
			}
		}
		getEditLoanSaveForm().setLoanVOInstanceMemberBackingList(memberBackingList);
	}

	@Override
	public void calculateEndDate() throws Throwable {
		// TODO Auto-generated method stub
		getLoanService().calculateLoanEndDate(getEditLoanSaveForm().getLoanVO());
	}

	@Override
	public void addInterest() throws Throwable {
		// TODO Auto-generated method stub
		getLoanService().getLoanInterest(getEditLoanSaveForm().getLoanVO());
	}

}